import type { Metadata } from "next";

import "../globals.css";
import Navbar from "@/app/components/navbar";

export const metadata: Metadata = {
  title: "Flysha - Website booking ticket",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section
      id="Signup"
      className="bg-[url('/assets/images/background/airplane.png')] bg-no-repeat bg-cover bg-left-top -z-10 min-h-screen text-white"
    >
      <div className="Header-content bg-gradient-to-r from-[#080318] to-[rgba(8,3,24,0)] z=0 pb-12 min-h-screen">
        <Navbar />
        {children}
      </div>
    </section>
  );
}
