import type { Metadata } from "next";

import "../globals.css";

export const metadata: Metadata = {
  title: "Flysha - Website booking ticket",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className="bg-flysha-black text-white">{children}</div>;
}
